//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence_Response
    {
        public int id { get; set; }
        public string superior_kpk { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public string kpk { get; set; }
        public Nullable<int> duration { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> response_time { get; set; }
    }
}
