//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOT_Toy_Nest
    {
        public int Id { get; set; }
        public string Nest { get; set; }
        public string Type { get; set; }
        public string Toy { get; set; }
        public string Peminjam_Terakhir { get; set; }
        public string Lokasi { get; set; }
        public string Status { get; set; }
    }
}
