//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DY_Improvement
    {
        public long impID { get; set; }
        public string kpk { get; set; }
        public string fullName { get; set; }
        public string mail { get; set; }
        public Nullable<System.DateTime> impDate { get; set; }
        public string impTitle { get; set; }
        public string impProblem { get; set; }
        public string impProblemPhoto { get; set; }
        public string impSolution { get; set; }
        public string impSolutionPhoto { get; set; }
        public string impValue { get; set; }
        public string impValueAddedMeasurement { get; set; }
        public string supportingFiles { get; set; }
        public string pdfFile { get; set; }
    }
}
