//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAP_Testing_FourWeeks
    {
        public string part { get; set; }
        public string desc { get; set; }
        public Nullable<int> w1 { get; set; }
        public Nullable<int> w2 { get; set; }
        public Nullable<int> w3 { get; set; }
        public Nullable<int> w4 { get; set; }
        public Nullable<int> w5 { get; set; }
        public long id { get; set; }
    }
}
