//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HC_Current_Copy
    {
        public string EMCMPY { get; set; }
        public string EMEMP_ { get; set; }
        public string EMNAME { get; set; }
        public string EMDEPT { get; set; }
        public string EMLOC_ { get; set; }
        public string EMJOBA { get; set; }
        public Nullable<decimal> EMBIRT { get; set; }
    }
}
