//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Items
    {
        public string Item_ID { get; set; }
        public string Item_Spesification { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Item_Qty { get; set; }
    }
}
