//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_Issue
    {
        public int Issue_Id { get; set; }
        public string issue_kb_id { get; set; }
        public string kpk { get; set; }
        public string Issue { get; set; }
        public string Action { get; set; }
        public string Line { get; set; }
        public string Scope { get; set; }
        public string Rplus { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string KB_Plant { get; set; }
        public string KB_Area { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
