//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_View_List_1
    {
        public string KB_id { get; set; }
        public string KbPlant { get; set; }
        public string KbMeetingPoint { get; set; }
        public string kbArea { get; set; }
        public string KbLine { get; set; }
        public string KbPpe { get; set; }
        public Nullable<System.DateTime> KbdatetimeStart { get; set; }
        public Nullable<System.DateTime> KbdatetimeEnd { get; set; }
        public string KbStatus { get; set; }
        public string KbAbsentStatus { get; set; }
        public Nullable<int> TotalMember { get; set; }
    }
}
