//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_View_Absent
    {
        public string KB_id { get; set; }
        public int absent_id { get; set; }
        public string kpk { get; set; }
        public Nullable<System.DateTime> absent_date { get; set; }
        public string Plant { get; set; }
        public string Fullname { get; set; }
        public string Dept { get; set; }
        public string Section { get; set; }
    }
}
