//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_View_Issue
    {
        public string KB_id { get; set; }
        public string KbPlant { get; set; }
        public string KbMeetingPoint { get; set; }
        public string kbArea { get; set; }
        public string KbLine { get; set; }
        public string KbPpe { get; set; }
        public string kpk { get; set; }
        public string Issue { get; set; }
        public string Action { get; set; }
        public string Line { get; set; }
        public string Scope { get; set; }
        public string Rplus { get; set; }
        public string Photo { get; set; }
        public string Fullname { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int Issue_Id { get; set; }
        public Nullable<System.Guid> id { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string Remarks { get; set; }
    }
}
