//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KF_Finding_Attach_Before
    {
        public int AttachBefID { get; set; }
        public string FindingID { get; set; }
        public string Before_attach { get; set; }
        public string Extention_before_attach { get; set; }
    }
}
