//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KF_Main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KF_Main()
        {
            this.KF_Background = new HashSet<KF_Background>();
            this.KF_Baseline = new HashSet<KF_Baseline>();
            this.KF_Date = new HashSet<KF_Date>();
            this.KF_Deliverable = new HashSet<KF_Deliverable>();
            this.KF_Goals = new HashSet<KF_Goals>();
            this.KF_Member = new HashSet<KF_Member>();
            this.KF_Scope = new HashSet<KF_Scope>();
        }
    
        public string Kaizen_ID { get; set; }
        public string Kaizen_title { get; set; }
        public string Kaizen_type { get; set; }
        public string Kaizen_dept { get; set; }
        public string Kaizen_room { get; set; }
        public string Kaizen_status { get; set; }
        public string Kaizen_madeby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Background> KF_Background { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Baseline> KF_Baseline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Date> KF_Date { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Deliverable> KF_Deliverable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Goals> KF_Goals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Member> KF_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KF_Scope> KF_Scope { get; set; }
    }
}
