//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KF_View_ListMemberAll
    {
        public string Kaizen_ID { get; set; }
        public string Kaizen_title { get; set; }
        public string Kaizen_type { get; set; }
        public string Kaizen_dept { get; set; }
        public string Kaizen_room { get; set; }
        public string Kaizen_status { get; set; }
        public string Kaizen_madeby { get; set; }
        public Nullable<System.DateTime> Kaizen_Create { get; set; }
        public Nullable<System.DateTime> Kaizen_DateTo { get; set; }
        public Nullable<System.DateTime> Kaizen_DateFrom { get; set; }
        public string kpkNum { get; set; }
        public string member_roles { get; set; }
        public string Fullname { get; set; }
        public string email { get; set; }
        public string Dept { get; set; }
        public string Section { get; set; }
        public string image { get; set; }
        public string pass { get; set; }
        public string level { get; set; }
        public long id { get; set; }
        public string CreatedBy { get; set; }
        public int MemberID { get; set; }
    }
}
