//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KF_VIEW_EMPLOYEE
    {
        public Nullable<System.Guid> id { get; set; }
        public string Plant { get; set; }
        public string KPK { get; set; }
        public string Fullname { get; set; }
        public string DeptCode { get; set; }
        public string SectCode { get; set; }
        public string Dept { get; set; }
        public string Section { get; set; }
    }
}
