//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KF_View_Dashboard
    {
        public string Kaizen_ID { get; set; }
        public string Kaizen_type { get; set; }
        public string Kaizen_title { get; set; }
        public string Kaizen_room { get; set; }
        public string Kaizen_dept { get; set; }
        public Nullable<System.DateTime> Kaizen_Create { get; set; }
        public Nullable<System.DateTime> Kaizen_DateFrom { get; set; }
        public Nullable<System.DateTime> Kaizen_DateTo { get; set; }
        public string Kaizen_status { get; set; }
    }
}
