//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_WindUser
    {
        public int userID { get; set; }
        public string windUser { get; set; }
        public string kpkNum { get; set; }
        public string pass { get; set; }
        public string status_log { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    }
}
