//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMS_Linus
    {
        public int linusID { get; set; }
        public string linusOtherID { get; set; }
        public string LinusTitle { get; set; }
        public string linusDescription { get; set; }
        public string linusStatus { get; set; }
        public Nullable<System.DateTime> linusCreateDate { get; set; }
        public string linusTitle { get; set; }
        public string linusRemaks { get; set; }
        public string linusFoto1 { get; set; }
        public string linusFoto2 { get; set; }
        public Nullable<System.DateTime> linusDateFrom_meeting { get; set; }
        public Nullable<System.DateTime> linusDateTo_meeting { get; set; }
        public string linusKpk { get; set; }
        public string linusFullname { get; set; }
        public string linusRoom { get; set; }
    }
}
