//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsForm_1
    {
        public long id { get; set; }
        public string kpk { get; set; }
        public string name { get; set; }
        public string remarks { get; set; }
        public string ResEmail { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public byte[] photo { get; set; }
    }
}
