//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pre_Kaizen_Form
    {
        public string fid_id { get; set; }
        public string kz_id { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string sponsor { get; set; }
        public string facilitator { get; set; }
        public string leader { get; set; }
        public string co_leader { get; set; }
        public string participant { get; set; }
        public string scope { get; set; }
        public string background { get; set; }
        public string baseline { get; set; }
        public string goals { get; set; }
        public string deliverables { get; set; }
        public string issue { get; set; }
        public string rootcause { get; set; }
        public string action { get; set; }
        public string area { get; set; }
    }
}
