//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment_MsForm
    {
        public long id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string e_ktp { get; set; }
        public string ktp_city { get; set; }
        public string dom_city { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string no_phone { get; set; }
        public string last_education { get; set; }
        public string major { get; set; }
        public Nullable<System.DateTime> vac1 { get; set; }
        public Nullable<System.DateTime> vac2 { get; set; }
        public Nullable<System.DateTime> vac3 { get; set; }
        public string agreement1 { get; set; }
        public string agreement2 { get; set; }
        public string status { get; set; }
    }
}
