//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Nest
    {
        public int No { get; set; }
        public string Nama { get; set; }
        public string KPK { get; set; }
        public string ID { get; set; }
        public string Username { get; set; }
    }
}
