//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robins_View_Booking
    {
        public long id { get; set; }
        public Nullable<long> room_id { get; set; }
        public string creator_kpk { get; set; }
        public string creator_name { get; set; }
        public string kaizen_id { get; set; }
        public string agenda { get; set; }
        public Nullable<System.DateTime> start_date_time { get; set; }
        public Nullable<System.DateTime> end_date_time { get; set; }
        public string room_name { get; set; }
        public string room_email { get; set; }
        public Nullable<long> group_id { get; set; }
        public Nullable<bool> has_computer { get; set; }
        public Nullable<bool> has_projector { get; set; }
        public Nullable<bool> has_screen { get; set; }
        public Nullable<bool> has_sound_system { get; set; }
        public Nullable<bool> has_board { get; set; }
        public Nullable<long> capacity { get; set; }
        public string group_name { get; set; }
        public string image_name { get; set; }
        public string plant { get; set; }
        public string area { get; set; }
        public string pic_name { get; set; }
        public string pic_email { get; set; }
    }
}
