//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robins_Integrated_Booking
    {
        public long id { get; set; }
        public Nullable<long> room_id { get; set; }
        public string creator_kpk { get; set; }
        public string creator_name { get; set; }
        public string kaizen_id { get; set; }
        public string agenda { get; set; }
        public Nullable<System.DateTime> start_date_time { get; set; }
        public Nullable<System.DateTime> end_date_time { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
