//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robins_Integrated_Room
    {
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<long> group_id { get; set; }
        public Nullable<bool> has_computer { get; set; }
        public Nullable<bool> has_projector { get; set; }
        public Nullable<bool> has_screen { get; set; }
        public Nullable<bool> has_sound_system { get; set; }
        public Nullable<bool> has_board { get; set; }
        public Nullable<long> capacity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
