//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testing
    {
        public long id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string shift { get; set; }
        public string machineNumber { get; set; }
        public string partNumber { get; set; }
        public string issues { get; set; }
        public string category { get; set; }
    }
}
