//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public string Finding_ID { get; set; }
        public string Kaizen_ID { get; set; }
        public string KPI { get; set; }
        public string Issue_desc { get; set; }
        public string Actions_desc { get; set; }
        public string Before_act { get; set; }
        public string After_act { get; set; }
        public string Unit_measure { get; set; }
        public string Goals_act { get; set; }
        public Nullable<System.DateTime> Due_date { get; set; }
        public string Remarks { get; set; }
        public string kpkNum { get; set; }
        public string Before_attach { get; set; }
        public string After_attach { get; set; }
        public string Extention_before_attach { get; set; }
        public string Extention_after_attach { get; set; }
    }
}
